[render]
version = "1"
mode = "git-linked"
service = "srv-replacewithserviceid"
repository = "OfficialBiohub/padma-lang"
branch = "main"
commit = "0123456789abcdef0123456789abcdef01234567"
rollback_deploy = "dep-replacewithdeployid"
